{"name": "test_three", "status": "failed", "statusDetails": {"message": "AssertionError: assert 6 > 11", "trace": "@allure.description_html(\"\"\"<h1>Html test description -- Test three </h1>\"\"\")\n    def test_three():\n    \n        mylogger.warning('O, O, an Oopsie')\n>       assert 6>11\nE       assert 6 > 11\n\nlogging2.py:40: AssertionError"}, "descriptionHtml": "<h1>Html test description -- Test three </h1>", "attachments": [{"name": "log", "source": "2f10d8cc-e6ce-45aa-8dc2-2da0a9e605df-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "a230eafa-a79f-49eb-b023-3cdcc6d8bc53-attachment.txt", "type": "text/plain"}], "start": 1589684145418, "stop": 1589684145419, "uuid": "1bcc9099-fef8-42b4-a9ab-5db180309faa", "historyId": "fbcfd7485c57aa105091ae2963a04874", "testCaseId": "5f820262070670c4d7cabe32948e0602", "fullName": "logging2#test_three", "labels": [{"name": "suite", "value": "logging2"}, {"name": "host", "value": "X"}, {"name": "thread", "value": "11004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "logging2"}]}